name: FTP Deploy to production.shiningdawn.in

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.optimus.herosite.pro
          username: vaikpvwe
          password: 7273OObjk*EHo#
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /production.shiningdawn.in/
          dangerous-clean-slate: true
          exclude: |
            .well-known/*
            cgi-bin/*
