name: Deploy HTML to production.shiningdawn.in via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.optimus.herosite.pro
          username: vaikpvwe
          password: 7273OObjk*EHo#
          port: 21
          protocol: ftp
          local-dir: ./    # Local directory to upload
          server-dir: /production.shiningdawn.in/  # Remote FTP path
